FROM python:3.12-slim AS base

COPY orm /app/orm
RUN pip install -e /app/orm

COPY server /app/server
RUN pip install --no-cache-dir -r /app/server/requirements.txt

EXPOSE 8000

WORKDIR /app

CMD ["gunicorn", "server.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "--log-level", "debug", "--access-logfile", "-", "--error-logfile", "-"]
