FROM node:24-slim AS builder

COPY client /app/client
WORKDIR /app/client

RUN npm install
RUN npm run build

FROM node:24-slim

WORKDIR /app
COPY --from=builder /app/client/build /app/build

EXPOSE 4173

CMD ["npx", "vite", "preview", "--host", "0.0.0.0", "--port", "4173"]
